version: '3.8'

services:
  php-apache:
    build: .
    ports:
      - "8000:80" # Exponer el puerto 80 del contenedor en el puerto 8000 de la máquina local
    volumes:
      - .:/var/www/html
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: test_db
      MARIADB_USER: usuario
      MARIADB_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
